spring:
  application:
    name: rbc
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: Openhere20*
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        default_schema: kras
    hibernate:
      ddl-auto: none